version: '3'
services:
  music:
    build: ./
    container_name: "test_containers"
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres
    container_name: "database"
    restart: always
    environment:
      POSTGRES_PASSWORD: example
